# .github/workflows/workflow.yml
name: CI/CD WORKFLOW
on:
  push:
    branches: [ main, developer ]  #kører til main og developer branches så.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package


#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: $
#          password: $
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: $/<your-api-name>:latest
